//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesPublishers
    {
        public int ID { get; set; }
        public int GameID { get; set; }
        public int PublisherID { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Publishers Publishers { get; set; }
    }
}
